[package]
name = "solana-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.1"
solana-sdk = "2.1"
solana-transaction-status = "2.1"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
